### ISSUE TITLE
Binding for Unified API

### ISSUE THREAD

**Issue by sainti** [PatternNZ/Xamarin-Moodstocks-Bindings#2]
Hi,
I'm trying to make binding to Moodstocks SDK for Xamarin Unified API based on this project (I need 64bit version). I managed to compile it but I have problem with syncing. I'm getting "unrecognized selector sent to instance" error when I'm calling SyncInBackground or SyncWithBackgroundWithBlock function.
Do you have any suggestions, how to make it work? Maybe you could update your project to include Unified API version?

Thanks
Marcin

**Comment by jamilgeor** [comment]
Hi Marcin,
I've just updated to Unified API.  Not sure if that will solve your issue.  If not, if you can provide a sample project I'll try and debug for you.

Thanks
Jamil

**Comment by sainti** [comment]
Hi
I've updated DLLs in my project and now it's working fine. 

Thank you very much. :+1:
Marcin
