### ISSUE TITLE
No class named AppDelegate is loaded

### ISSUE THREAD

**Issue by MrGrabazu** [PatternNZ/Xamarin-Moodstocks-Bindings#3]
Hi folks,

I work on iOS application on Xamarin and want to add moodstocks.
I found your project on Moddstocks website, and get it, build it in release mode and add the moddstocks.dll file in reference to my ios project in Xamarin.

Since I have an issue on the application init (see the joined [screenshot](https://cloud.githubusercontent.com/assets/6928672/13983190/81ed3ea4-f0ee-11e5-832d-aac9b6f215f5.png)).

I can't foind why I have this error when I add the moodstocks.dll to my project and don't have it when I remove the dll from references. So I think it is related to the moodstocks.dll but I don't find out why...

Have you any idea from what that come from ?

Thank you for your help :)

**Comment by jamilgeor** [comment]
Hi,
I'm not sure to be honest, do you have a class called "AppDelegate" in your project?  Are you able to share your source with me so that I can have a better look for you.  jamil at pattern.co.nz

Thanks
Jamil

**Comment by MrGrabazu** [comment]
Hi,

Shame on me, I rename the resulted DLL Moodstocks.IOS.dll for my needs and to differentiate it from the futur potential android DLL (when I found a way to have one..) in my ThirdPartyDlls directory.
I rename it as Moodstocks.dll and all is fine... 

Xamarin was a bit greedy with intel about the issue..

Have you an idea if there is any way to give the name I want to this DLL without broke my app launch ?

By the way thank you for your answer.
If you have an answer for my last question I'll take it, and you can close this ticket, the issue is not yours ! :)

Kevin.

**Comment by jamilgeor** [comment]
Hi Kevin,
You could just compile the project from source, and rename the output DLL that way.  It's a fairly small project so should be easy to build.  Let me know if you run into any issues building it yourself.

Thanks
Jamil
